version: 2

models:
  - name: stg_products
    description: "Staging table for products with cleaned price data"
    columns:
      - name: product_id
        description: "Product identifier (includes -1 for unknown products)"
        tests:
          - not_null
          - unique
      
      - name: product_name
        description: "Name of the product"
        tests:
          - not_null
      
      - name: min_price_original
        description: "Minimum price in original currency"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      
      - name: max_price_original
        description: "Maximum price in original currency"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      
      - name: price_currency
        description: "Currency code for prices"
        tests:
          - not_null
          - accepted_values:
              values: ['EUR', 'USD', 'BGN', 'GBP', 'TRY', 'PLN']

  - name: stg_sales_orders
    description: "Staging table for sales orders"
    columns:
      - name: mongo_id
        tests:
          - not_null
      
      - name: order_id
        tests:
          - not_null
      
      - name: user_id
        tests:
          - not_null
      
      - name: product_id
        tests:
          - not_null
      
      - name: quantity
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"
      
      - name: price_original
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0"
      
      - name: currency_code
        tests:
          - not_null
      
      - name: order_date
        tests:
          - not_null
      
      - name: event_ts
        tests:
          - not_null

  - name: stg_ip_locations
    description: "Staging table for IP locations"
    columns:
      - name: ip_address
        tests:
          - not_null
      
      - name: location_key
        tests:
          - not_null
      
      - name: country_name
        tests:
          - not_null